# SPDX-FileCopyrightText: 2025 Chen Linxuan <me@black-desk.cn>
# SPDX-License-Identifier: MIT

name: "Build and Deploy Kernel Code Browser to GitHub Pages"

on:
  # Run on manual trigger
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Linux kernel version/tag to build (e.g., v6.12, master)'
        required: false
        default: 'master'
        type: string
      kernel_config:
        description: 'Kernel configuration to use'
        required: false
        default: 'defconfig'
        type: choice
        options:
          - 'defconfig'
          - 'allmodconfig'
          - 'allyesconfig'
      arch:
        description: 'Target architecture'
        required: false
        default: 'x86_64'
        type: choice
        options:
          - 'x86_64'
          - 'arm64'
          - 'arm'
  # Run weekly on Sunday at 3:00 UTC to build latest master
  schedule:
    - cron: '0 3 * * 0'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  KERNEL_REPO: https://github.com/torvalds/linux.git

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    outputs:
      kernel-version: ${{ steps.kernel-info.outputs.version }}
      kernel-commit: ${{ steps.kernel-info.outputs.commit }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set build parameters
        id: params
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "kernel_version=${{ inputs.kernel_version }}" >> $GITHUB_OUTPUT
            echo "kernel_config=${{ inputs.kernel_config }}" >> $GITHUB_OUTPUT
            echo "arch=${{ inputs.arch }}" >> $GITHUB_OUTPUT
          else
            echo "kernel_version=master" >> $GITHUB_OUTPUT
            echo "kernel_config=defconfig" >> $GITHUB_OUTPUT
            echo "arch=x86_64" >> $GITHUB_OUTPUT
          fi

      - name: Create workspace directories
        run: |
          mkdir -p kernel-source
          mkdir -p kernel-build

      - name: Cache kernel source
        id: cache-source
        uses: actions/cache@v4
        with:
          path: kernel-source/
          key: kernel-source-${{ steps.params.outputs.kernel_version }}
          restore-keys: |
            kernel-source-${{ steps.params.outputs.kernel_version }}

      - name: Cache kernel build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: kernel-build/
          key: kernel-build-${{ steps.params.outputs.kernel_version }}-${{ steps.params.outputs.kernel_config }}-${{ steps.params.outputs.arch }}
          restore-keys: |
            kernel-build-${{ steps.params.outputs.kernel_version }}-${{ steps.params.outputs.kernel_config }}-
            kernel-build-${{ steps.params.outputs.kernel_version }}-

      - name: Clone Linux kernel
        if: steps.cache-source.outputs.cache-hit != 'true'
        run: |
          cd kernel-source
          git clone --depth 1 --branch ${{ steps.params.outputs.kernel_version }} ${{ env.KERNEL_REPO }} linux
          cd linux
          echo "Cloned Linux kernel ${{ steps.params.outputs.kernel_version }}"
          git log --oneline -1
      - name: Update Linux kernel
        if: steps.cache-source.outputs.cache-hit == 'true'
        run: |
          cd kernel-source/linux
          git pull || true
          echo "Updated Linux kernel ${{ steps.params.outputs.kernel_version }}"
          git log --oneline -1

      - name: Get kernel information
        id: kernel-info
        run: |
          cd kernel-source/linux
          KERNEL_VERSION=$(make kernelversion)
          KERNEL_COMMIT=$(git rev-parse --short HEAD)
          echo "version=${KERNEL_VERSION}" >> $GITHUB_OUTPUT
          echo "commit=${KERNEL_COMMIT}" >> $GITHUB_OUTPUT
          echo "Kernel version: ${KERNEL_VERSION}"
          echo "Kernel commit: ${KERNEL_COMMIT}"

      - name: Build kernel with compile_commands.json
        run: |
          docker run --rm \
            -v $(pwd)/kernel-source:/mnt/source:ro \
            -v $(pwd)/kernel-build:/mnt/build \
            ${{ env.REGISTRY }}/${{ github.repository }}/kernel-build:latest \
            /mnt/scripts/kernel-build.sh \
              -s /mnt/source/linux \
              -b /mnt/build \
              -c ${{ steps.params.outputs.kernel_config }} \
              -a ${{ steps.params.outputs.arch }}

      - name: Verify build artifacts
        run: |
          echo "Build artifacts:"
          ls -la kernel-build/
          if [[ -f kernel-build/compile_commands.json ]]; then
            echo "Compile commands file size:"
            du -h kernel-build/compile_commands.json
          else
            echo "Warning: compile_commands.json not found, may be using cached version"
          fi

      - name: Compress kernel artifacts
        run: |
          tar -czf kernel-source.tar.gz kernel-source/
          tar -czf kernel-build.tar.gz kernel-build/
          echo "Compressed artifacts:"
          ls -lh kernel-*.tar.gz

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: |
            kernel-source.tar.gz
            kernel-build.tar.gz
          retention-days: 1

  generate-codebrowser:
    needs: build-kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download kernel artifacts
        uses: actions/download-artifact@v4
        with:
          name: kernel-artifacts

      - name: Extract kernel artifacts
        run: |
          tar -xzf kernel-source.tar.gz
          tar -xzf kernel-build.tar.gz
          rm kernel-*.tar.gz
          echo "Extracted kernel artifacts:"
          ls -la kernel-source/linux/ kernel-build/

      - name: Create output directory
        run: |
          mkdir -p codebrowser-output

      - name: Generate codebrowser HTML
        run: |
          docker run --rm \
            -v $(pwd)/kernel-source:/mnt/source:ro \
            -v $(pwd)/kernel-build:/mnt/build:ro \
            -v $(pwd)/codebrowser-output:/mnt/output \
            ${{ env.REGISTRY }}/${{ github.repository }}/codebrowser:latest \
            /mnt/scripts/generate-codebrowser.sh \
              -i /mnt/source/linux \
              -b /mnt/build \
              -o /mnt/output \
              -p "Linux Kernel" \
              -v "${{ needs.build-kernel.outputs.kernel-version }} (${{ needs.build-kernel.outputs.kernel-commit }})"

      - name: Verify codebrowser output
        run: |
          echo "Codebrowser output structure:"
          find codebrowser-output/ -type f | head -20
          echo "Root directory contents:"
          ls -la codebrowser-output/
          echo "Checking for index.html in root:"
          if [[ -f codebrowser-output/index.html ]]; then
            echo "✓ index.html found in root"
          else
            echo "✗ index.html not found in root - checking subdirectories:"
            find codebrowser-output/ -name "index.html"
          fi
          echo "Checking for data directory and CSS files:"
          if [[ -d codebrowser-output/data ]]; then
            echo "Data directory exists:"
            ls -la codebrowser-output/data/
          else
            echo "Warning: Data directory not found!"
          fi
          echo "Total size:"
          du -sh codebrowser-output/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'codebrowser-output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
